### PR TITLE
Sprint 1

### PR DESCRIPTION
**Pull request by Sagar7421**
Added Template for minutes of meeting file.

Added Minutes of Meeting for 8th July. 

Initialized backend with Nodejs, ExpressJs, and Backend.

### CODE REVIEW

**Review by anuragagarwal6895 — DISMISSED** [review]
Hi @Sagar7421 

Your changes are reviewed from my side. kindly proceed with the merge process.

**Review by KarnikShah — APPROVED** [review]
All files reviewed.

**Review by aksharpatel17 — DISMISSED** [review]
Hi @Sagar7421 , @anuragagarwal6895 

All changes look good to me.
Go ahead with merge.

**Review by anuragagarwal6895 — APPROVED** [review]
Hi @Sagar7421 

Changes Look good to me.

**Review by aksharpatel17 — APPROVED** [review]
Changes are approved

**Pull request merged**
